import json
from collections import Counter, defaultdict
from pathlib import Path

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Uses the records.jsonl generated by record-aggregator and
# generates a JSON file with records for each author.
# Current data:
#   - Number of papers
#   - Categories written in
#   - Top Collaborators
# ToDo:
#   - Category Weights
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


RECORDS = Path("records.jsonl")
AUTHORS = Path("authors.json")

ALIASES = {
    "math-ph": "math.MP",
    "cs.IT": "math.IT",
    "cs.NA": "math.NA",
    "stat.TH": "math.ST",
}

def canonical(cat):
    return ALIASES.get(cat, cat)


## Opens the records file and yields record json object line
def load_records():
    with RECORDS.open(encoding = "utf-8") as rf:
        for line in rf:
            yield json.loads(line)

## Returns a key to be used for the given author.
def author_key(author):
    keyname = (author.get("keyname") or "").strip().lower().replace(".","").replace(" ", "_")
    forenames = (author.get("forenames") or "").strip().lower().replace(" ", "_").replace(".", "")
    return f"{keyname}_{forenames}"

## Returns a dict per author from paired data built in count-papers.
def group_by_author(cntr):
    group = defaultdict(Counter)
    for (key, cat), n in cntr.items():
        group[key][cat] = n
    return {key: dict(c.most_common()) for key, c in group.items()}


## Returns counters of the number of papers and categories associated to each author.
def count_papers():
    papers = Counter() # counter for number of papers
    listed_cats = Counter() # counter for categories of papers
    listed_authors = Counter()
    display = {}

    for rec in load_records():
        rec_cats = {canonical(cat) for cat in rec.get("categories", [])}
        rec_auth = {author_key(a) for a in rec["authors"]}

        for a in rec["authors"]:
            key = author_key(a)
            papers[key] += 1 #add 1 count to papers for each author that appears in record
            for cat in rec_cats:
                listed_cats[(key, cat)] += 1
            for auth in rec_auth:
                if auth != key:
                    listed_authors[(key, auth)] += 1
            display.setdefault(key, f"{a.get("forenames") or ""} {a.get("keyname") or ""}".strip())
    
    return papers, listed_cats, listed_authors, display

## Calls the functions to gather author data and then dump to file.
def generate_author_list():
    papers, listed_cats, listed_authors, display = count_papers()
    cats = group_by_author(listed_cats)
    auths = group_by_author(listed_authors)
    data = {
        key: {
            "name": display[key],
            "papers": n,
            "categories": cats.get(key, {}),
            "collaborators": auths.get(key, {})
        }
        for key, n in papers.most_common()
    }
    dump_authors(data)


def dump_authors(authors):
    with AUTHORS.open("w", encoding="utf-8") as af:
        json.dump(authors, af, indent = 2, ensure_ascii = False)
    print(f"Wrote to {str(AUTHORS)} with {len(authors)} entries")

generate_author_list()