from pathlib import Path
import xml.etree.ElementTree as ET
import json

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Gathers the data generated by data-generator and creates
# objects with the information from each record. Stores the
# record objects in ./records.jsonl
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

OA = "{http://www.openarchives.org/OAI/2.0/}"
ARX = "{http://arxiv.org/OAI/arXiv/}"

RESULTS = Path("results") #Path to folder of raw xml data from API endpoint
RESULTS.mkdir(exist_ok=True)

RECORDS = Path("records.jsonl")

## Returns the list of paths for the xml results generated from the API.
def fetch_result_paths():
    return list(RESULTS.glob("results-*.xml"))

## Returns a json record object from the data stripped from record.
def strip_record(record):
    arxiv = record.find(f"{OA}metadata/{ARX}arXiv")
    if arxiv is None:
        return None
    
    authors = []

    for a in arxiv.findall(f"{ARX}authors/{ARX}author"):
        keyname = a.findtext(f"{ARX}keyname")
        fornames = a.findtext(f"{ARX}forenames")
        authors.append({"keyname" : keyname, "forenames" : fornames})

    cats = (arxiv.findtext(f"{ARX}categories") or "").split()

    return{
        "id" : arxiv.findtext(f"{ARX}id"),
        "title" : arxiv.findtext(f"{ARX}title") or "",
        "created" : arxiv.findtext(f"{ARX}created"),
        "categories" : cats,
        "primary" : cats[0] if cats else None,
        "authors" : authors
    }

## A yield iterator on which returns the path strings for the records.
def iterate_records():
    for path in fetch_result_paths():
        root = ET.fromstring(path.read_text(encoding="utf-8"))
        for record in root.findall(f".//{OA}record"):
            rec = strip_record(record)
            if rec is not None:
                yield rec

## Writes the records to file.
def dump_records():
    n = 0
    with RECORDS.open("w", encoding="utf-8") as rf:
        for record in iterate_records():
            rf.write(json.dumps(record, ensure_ascii=False) + "\n")
            n += 1
    print(f"Populated {str(RECORDS)} with {n} records.")

dump_records()
    